# # a =37
# # b = float(a)
# # print(b)
# # print (type(b)) 
# a = ("4567")
# print(type(a))
# b = int(a)
# print(b)
# print(type(b))
a = ("457.87")
print(type(a))
b1 = float(a)
print(b1)
b2 = int(b1)
print(b2)
print(type(b2))