x=int(input("enter first number - "))
y=int(input("enter second number - "))
print("sum is = ",x+y)
print("difference is",x-y)
print("multiply is",x*y)
print("division is",x/y)
print("modulus is",x%y)
print("exponential is",x**y)
print("floor division is",x//y)
