x=int(input("enter first number - "))
y=int(input("enter second number - "))
print("the is == ",x==y)
print("the is != ",x!=y)
print("the is > ",x>y)
print("the is >= ",x>=y)
print("the is < ",x<y)
print("the is <=",x<=y)
#print("the is",x//y)